COLUMNS:
  url: object 
  fetch_date: object 
  house_type: object 
  bathrooms: int64  
  bedrooms: int64  
  price: float64
  locality: object 
  Condition: object 
  Furnishing: object 
  Property Size: float64
  24-hour Electricity: int64  
  Air Conditioning: int64  
  Apartment: int64  
  Balcony: int64  
  Chandelier: int64  
  Dining Area: int64  
  Dishwasher: int64  
  Hot Water: int64  
  Kitchen Cabinets: int64  
  Kitchen Shelf: int64  
  Microwave: int64  
  Pop Ceiling: int64  
  Pre-Paid Meter: int64  
  Refrigerator: int64  
  TV: int64  
  Tiled Floor: int64  
  Wardrobe: int64  
  Wi-Fi: int64  
  loc: object

TAREGT_COLUMN:
  name: price