artifacts_root: artifacts

data_validation:
  root_dir: artifacts/pipeline/data_validation
  data_dir: artifacts/data/01-raw/raw.csv
  STATUS_FILE: artifacts/pipeline/data_validation/status.txt


data_split:
  root_dir: artifacts/pipeline/data_split
  data_dir: artifacts/data/01-raw/raw.csv
  

data_processing:
  root_dir: artifacts/pipeline/data_preprocess
  data_dir: artifacts/data/01-raw/raw.csv
  train: artifacts/pipeline/data_split/train.csv
  test: artifacts/pipeline/data_split/eval.csv
  geocode_cache: artifacts/cache/geocode_cache.json