name: Deploy to Cloud Run

on: 
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download & Unzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download ${{ github.event.release.tag_name }} -p "artifacts.zip"
          unzip -o artifacts.zip

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with: 
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: Setup Cloud Run
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ares-repo/ares-app:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ares-repo/ares-app:${{ github.sha }}
        
      - name: Run
        run: |
          gcloud run deploy ares-service \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ares-repo/ares-app:${{ github.sha }} \
            --region us-central1 \
            --allow-unauthenticated
      
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: ${{ secrets.GCP_PROJECT_ID }}
          channelId: lives
